namespace KitchenPC.Modeler
{
    using System;
    using System.Linq;

    /// <summary>
    /// This contains a model generated by a modeling session.  The RecipeIDs contain the suggested recipes to make, and the leftover amounts indicate
    /// the quantity of given ingredients that would be left in the user's pantry after making the suggested recipes.
    /// </summary>
    public class Model
    {
        private readonly Guid[] recipeIds;
        private readonly PantryItem[] pantry;
        private readonly double score;

        public Model(RecipeNode[] recipes, PantryItem[] pantry, double score)
        {
            this.recipeIds = recipes.Select(r => { return r.RecipeId; }).ToArray();
            this.pantry = pantry;
            this.score = score;
        }

        public Guid[] RecipeIds
        {
            get
            {
                return this.recipeIds;
            }
        }

        public PantryItem[] Pantry
        {
            get
            {
                return this.pantry;
            }
        }

        public int Count
        {
            get
            {
                return this.recipeIds.Length;
            }
        }

        public double Score
        {
            get
            {
                return this.score;
            }
        }
    }
}